#!/usr/bin/env python3
"""Builds game/font.js from font/font5x7.txt.

  python3 font/make_font.py           write game/font.js
  python3 font/make_font.py --check   fail if game/font.js is out of date
  python3 font/make_font.py --sheet out.png   also draw every glyph to a PNG (needs Pillow)

Packed format: for every glyph — the character, its width (1..5) and 10 rows as base-32 digits
(row 0 = accent row above the capitals, rows 1..7 = capital height, rows 8..9 = descenders);
the leftmost pixel of a row is the highest bit.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'font5x7.txt')
OUT = os.path.join(HERE, '..', 'game', 'font.js')
B32 = '0123456789abcdefghijklmnopqrstuv'
ROWS = 10


def parse(path):
    glyphs, order, cur = {}, [], None
    for n, raw in enumerate(open(path, encoding='utf-8'), 1):
        line = raw.rstrip('\n')
        if not line.strip() or line.startswith('# '):
            continue
        if line.startswith('== '):
            head = line[3:]
            ch, rest = head[0], head[1:].strip()
            if ch in glyphs:
                sys.exit(f'{path}:{n}: glyph {ch!r} defined twice')
            if rest.startswith('='):
                src = rest[1:].strip()
                if src not in glyphs:
                    sys.exit(f'{path}:{n}: {ch!r} = {src!r}, but {src!r} is not defined above')
                glyphs[ch] = dict(glyphs[src]); cur = None
            else:
                cur = {'accent': rest == '^', 'rows': [], 'line': n}; glyphs[ch] = cur
            order.append(ch)
            continue
        if cur is None or any(c not in '.#' for c in line):
            sys.exit(f'{path}:{n}: unexpected line {line!r}')
        cur['rows'].append(line)
    for ch in order:
        g = glyphs[ch]; rows = g['rows']
        w = {len(r) for r in rows}
        if len(w) != 1 or max(w) > 5:
            sys.exit(f"{path}:{g['line']}: {ch!r}: rows must all have the same width, at most 5")
        full = rows if g['accent'] else ['.' * len(rows[0])] + rows
        if len(full) > ROWS:
            sys.exit(f"{path}:{g['line']}: {ch!r}: too many rows ({len(rows)})")
        g['full'] = full + ['.' * len(rows[0])] * (ROWS - len(full))
    return glyphs, order


def pack(g):
    rows = g['full']
    cols = [i for i in range(len(rows[0])) if any(r[i] == '#' for r in rows)]
    if not cols:
        return 1, '0' * ROWS
    a, b = cols[0], cols[-1] + 1
    return b - a, ''.join(B32[int(r[a:b].replace('.', '0').replace('#', '1'), 2)] for r in rows)


def js_source(data):
    lit = "'" + data.replace('\\', '\\\\').replace("'", "\\'") + "'"
    return TEMPLATE.replace('@DATA@', lit)


TEMPLATE = r'''/* Sonaroids pixel font 5x7 (Latin, Cyrillic, digits, punctuation).
   GENERATED by font/make_font.py from font/font5x7.txt - edit the .txt, not this file.
   PF.draw(ctx, text, x, y, scale, color) draws in game pixels; y is the top of the capitals. Returns the width.
   PF.width(text, scale), PF.wrap(text, maxWidth, scale) -> lines, PF.has(char). */
var PF=(function(){
  var D=@DATA@, G={}, B='0123456789abcdefghijklmnopqrstuv';
  for(var i=0;i<D.length;i+=12){ var r=[]; for(var k=0;k<10;k++) r.push(B.indexOf(D[i+2+k])); G[D[i]]={w:+D[i+1],r:r}; }
  var SPACE=3, GAP=1;
  function glyph(c){ return G[c]||G['?']; }
  function width(s,sc){ sc=sc||1; var x=0; for(var i=0;i<s.length;i++) x+=(s[i]===' '?SPACE:glyph(s[i]).w)+GAP; return Math.max(0,x-GAP)*sc; }
  function draw(ctx,s,x,y,sc,col){ sc=sc||1; if(col) ctx.fillStyle=col; var cx=x;
    for(var i=0;i<s.length;i++){ if(s[i]===' '){ cx+=(SPACE+GAP)*sc; continue; } var g=glyph(s[i]);
      for(var k=0;k<10;k++){ var b=g.r[k]; if(b) for(var j=0;j<g.w;j++) if(b&(1<<(g.w-1-j))) ctx.fillRect(cx+j*sc,y+(k-1)*sc,sc,sc); }
      cx+=(g.w+GAP)*sc; }
    return cx-x-GAP*sc; }
  function wrap(s,maxW,sc){ var out=[], line=''; s.split(' ').forEach(function(w){ var t=line?line+' '+w:w;
    if(line&&width(t,sc)>maxW){ out.push(line); line=w; } else line=t; }); if(line) out.push(line); return out; }
  return {draw:draw,width:width,wrap:wrap,has:function(c){ return c===' '||!!G[c]; },CAP:7,LINE:12};
})();
if(typeof module!=='undefined') module.exports=PF;
'''


def sheet(path, glyphs, order):
    from PIL import Image, ImageDraw
    S, cell, per = 6, 8, 24
    rows = (len(order) + per - 1) // per
    im = Image.new('RGB', (per * cell * S + 2 * S, rows * 12 * S + 2 * S), (27, 26, 46))
    d = ImageDraw.Draw(im)
    for n, ch in enumerate(order):
        w, bits = pack(glyphs[ch])
        ox, oy = S + (n % per) * cell * S, S + (n // per) * 12 * S
        d.rectangle([ox, oy + S, ox + 5 * S - 1, oy + 8 * S - 1], fill=(42, 36, 64))
        for k, c in enumerate(bits):
            v = B32.index(c)
            for j in range(w):
                if v & (1 << (w - 1 - j)):
                    d.rectangle([ox + j * S, oy + k * S, ox + (j + 1) * S - 1, oy + (k + 1) * S - 1], fill=(255, 243, 234))
    im.save(path)


if __name__ == '__main__':
    glyphs, order = parse(SRC)
    data = ''.join(ch + str(w) + bits for ch in order for w, bits in [pack(glyphs[ch])])
    src = js_source(data)
    if '--check' in sys.argv:
        ok = os.path.exists(OUT) and open(OUT, encoding='utf-8').read() == src
        print('game/font.js is up to date' if ok else 'game/font.js is OUT OF DATE: run python3 font/make_font.py')
        sys.exit(0 if ok else 1)
    open(OUT, 'w', encoding='utf-8').write(src)
    print(f'{len(order)} glyphs, {len(src.encode())} bytes -> game/font.js')
    if '--sheet' in sys.argv:
        sheet(sys.argv[sys.argv.index('--sheet') + 1], glyphs, order)
