"""The palms of the getting-ready pictures in HD (v1.05; the maintainer's picks, 1 Oct 2026): drawn by promo/promo_hand.py in the games'
own oblique projection (screen x = X + 0.42·Y, y = 0.62·Y − Z; X along the phone, Y toward the player, Z up), so they sit in the
pictures exactly as the pixel palms did:
  table — the right palm flat over the table, fingers away, the thumb toward the phone («на столе — норм»);
  end   — the right palm edge down at the phone's end, facing it; the thumb thicker and shorter, the fingers a little thicker;
  hold  — the left hand holding the phone from below: fingers up its far side and onto it, the thumb under it; the parts the phone
          hides are left out, so the picture goes on top of the phone (fingers shorter and thicker, the palm wider).
Each is kept as WebP in src/42_hands.js with the pixel where its wrist is and its scale (px per cm of the hand).
Run from the repository: python3 hands/make_hands.py   (needs numpy and Pillow; then python3 build.py)"""
import os, sys, io, base64, json, math
import numpy as np
from PIL import Image
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'); sys.path.insert(0, os.path.join(ROOT, 'promo')); import promo_hand as H
PPCM = 24                                        # px per cm of the hand in the stored pictures
def M(cols): return np.array(cols, float).T      # where the hand's X (toward the pinky), Y (fingers), Z (back) go: x right, y up, z toward the player
SPECS = {
    'table': dict(R=M([[1, 0, 0], [0, 0, -1], [0, 1, 0]]), pose='relaxed'),
    'end':   dict(R=M([[0, -1, 0], [0, 0, -1], [1, 0, 0]]), pose='end'),
    # the phone, in the hand's cm around the wrist (x, up, toward the player): the wrist 0.5 cm inside the near edge, 2.2 cm under the phone
    'hold':  dict(R=M([[1, 0, 0], [0, 0, -1], [0, -1, 0]]), pose='hold', wide=1.15, occ=((0.0, 2.7, -5.26), (12.0, 0.5, 5.76))),
}
out = ['/* generated by hands/make_hands.py — the HD palms of the getting-ready pictures: WebP, the wrist at (ox, oy), PPCM px per cm */', 'var HAND_PICS={']
for name, sp in SPECS.items():
    W = Hh = 36 * PPCM
    tmp = os.path.join(ROOT, 'hands', '_' + name + '.png')
    H.render(pose=sp['pose'], out=tmp, W=W, H=Hh, ppcm=PPCM, ss=2, cx=0, cy=0, rigY=0, rigX=0, handA=0, extra=sp['R'], sleeve=True, fadeL=8,
             wide=sp.get('wide', 1.0), oblique=(0.42, 0.62), occ=sp.get('occ'))
    im = Image.open(tmp); bb = im.getbbox(); im = im.crop(bb); os.remove(tmp)
    buf = io.BytesIO(); im.save(buf, 'WEBP', quality=82, method=6); b = buf.getvalue()
    out.append("  %s:{ox:%d,oy:%d,w:%d,h:%d,src:'data:image/webp;base64,%s'}," % (name, W // 2 - bb[0], Hh // 2 - bb[1], im.width, im.height, base64.b64encode(b).decode()))
    print(name, im.size, round(len(b) / 1024), 'KB')
out.append('  ppcm:%d };' % PPCM)
open(os.path.join(ROOT, 'src', '42_hands.js'), 'w').write('\n'.join(out) + '\n')
